#!/usr/bin/env python3
"""
make_training_fc.py -- emit the plot feature table as Earth Engine source.

make_annual_series.js classifies in the cloud and needs the training rows in
the same 40 columns, in the same order, as the local model saw. Rather than
uploading an asset, the table is printed as a FeatureCollection literal that
can be pasted straight into the script.

Usage
-----
    python3 make_training_fc.py --features features.csv > training_fc.js
"""

import argparse

import pandas as pd

CLASS_ID = {"Swamp": 0, "Temporary floodplain": 1,
            "Temporary ponds": 2, "Terrestrial saline flats": 3}


def main(features_csv, epoch):
    df = pd.read_csv(features_csv)
    if epoch != "both":
        df = df[df["epoch"] == epoch]
    drop = ["plot", "epoch", "subtype", "n_obs", "block"]
    cols = [c for c in df.columns if c not in drop]

    print("// Generated by make_training_fc.py -- do not edit by hand.")
    print("// %d training rows, %d predictors, epoch '%s'."
          % (len(df), len(cols), epoch))
    print("var PREDICTORS = [%s];"
          % ", ".join(f"'{c}'" for c in cols))
    print("var TRAINING = ee.FeatureCollection([")
    out = []
    for _, r in df.iterrows():
        props = ", ".join(f"{c}: {r[c]:.6g}" for c in cols)
        out.append("  ee.Feature(null, {%s, class_id: %d})"
                   % (props, CLASS_ID[r["subtype"]]))
    print(",\n".join(out))
    print("]);")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--features", default="features.csv")
    ap.add_argument("--epoch", default="both",
                    choices=["both", "baseline", "present"])
    a = ap.parse_args()
    main(a.features, a.epoch)
